version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    parameters:
      domain:
        type: string
    steps:
      - checkout
      - run:
          name: Build static files
          command: |
            npm install
            npx honkit build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  push:
    docker:
      - image: circleci/node:16
    parameters:
      cfpage:
        type: string
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Push static files to Cloudflare
          command: npx wrangler pages deploy build --project-name=<< parameters.cfpage >>

workflows:
  version: 2
  pipeline:
    jobs:
      - build:
          name: docs/build
          domain: docs.1delta.io
          filters:
            branches:
              only: main
      - push:
          name: docs/push
          cfpage: docs-1delta
          requires:
            - docs/build